import { ChatLog } from "@/component/chatLog";
import { answerData } from "@/Q&A/AnswerData";
import { ChatLogInfo } from "@/type/chatLogInfo";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [messageLogs, setMessageLog] = useState<ChatLogInfo[]>(answerData);

  return (
    <>
      <Head>
        <title>質問への回答</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="chatArea">
        <ChatLog messageLog={messageLogs} />
      </div>
    </>
  );
}
